# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkLayer_RxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetworkLayer_RxSwift

	pod 'RxSwift'
	pod 'RxCocoa'

  target 'NetworkLayer_RxSwiftTests' do
    inherit! :search_paths
    pod 'RxSwift'
    pod 'RxCocoa'
  end

  target 'NetworkLayer_RxSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
